/* ─── Reports Page ─── */
import { useState, useEffect, useRef } from 'react';
import { FileText, Printer, Download, Calendar, Clock, AlertTriangle } from 'lucide-react';
import { getIncidents, getAnalytics, getRecommendation } from '../services/api';
import type { Incident, Analytics, Recommendation } from '../types';

export default function Reports() {
    const [incidents, setIncidents] = useState<Incident[]>([]);
    const [analytics, setAnalytics] = useState<Analytics | null>(null);
    const [selectedInc, setSelectedInc] = useState<Incident | null>(null);
    const [rec, setRec] = useState<Recommendation | null>(null);
    const [generating, setGenerating] = useState(false);
    const reportRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        Promise.all([getIncidents(), getAnalytics()])
            .then(([i, a]) => { setIncidents(i); setAnalytics(a); });
    }, []);

    const generateReport = async (inc: Incident) => {
        setGenerating(true);
        setSelectedInc(inc);
        try { setRec(await getRecommendation(inc.id)); } catch { setRec(null); }
        setGenerating(false);
    };

    const handlePrint = () => {
        if (reportRef.current) {
            const w = window.open('', '', 'width=800,height=600');
            if (w) {
                w.document.write(`
          <html><head><title>CrisisFlow Report - ${selectedInc?.id}</title>
          <style>body{font-family:Inter,sans-serif;padding:40px;color:#1a1a1a}
          h1{color:#1e3a5f;border-bottom:2px solid #ef4444;padding-bottom:8px}
          h2{color:#334155;margin-top:20px}
          .badge{display:inline-block;padding:2px 8px;border-radius:100px;font-size:11px;font-weight:600}
          .critical{background:#fee2e2;color:#ef4444}
          .high{background:#fff7ed;color:#f97316}
          table{width:100%;border-collapse:collapse;margin:10px 0}
          td,th{border:1px solid #e2e8f0;padding:8px;text-align:left;font-size:13px}
          th{background:#f8fafc;font-weight:600}
          .footer{margin-top:30px;border-top:1px solid #e2e8f0;padding-top:10px;font-size:11px;color:#94a3b8}
          </style></head><body>
          ${reportRef.current.innerHTML}
          <div class="footer">Generated by CrisisFlow | ${new Date().toLocaleString()} | Data Source: Simulation</div>
          </body></html>
        `);
                w.document.close();
                w.print();
            }
        }
    };

    const sevBadge = (s: string) => `<span class="badge ${s === 'Critical' ? 'critical' : 'high'}">${s}</span>`;

    return (
        <div className="space-y-4">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-xl font-bold text-white flex items-center gap-2">
                        <FileText size={22} className="text-crisis-cyan" /> Reports
                    </h1>
                    <p className="text-xs text-slate-500 mt-0.5">Generate emergency incident reports</p>
                </div>
            </div>

            {/* Summary Analytics */}
            {analytics && (
                <div className="card p-4">
                    <h3 className="text-sm font-semibold text-white mb-3">System Summary</h3>
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
                        <div><span className="text-slate-500">Total Incidents:</span> <span className="text-white font-bold">{analytics.total_incidents}</span></div>
                        <div><span className="text-slate-500">Active:</span> <span className="text-crisis-red font-bold">{analytics.active_incidents}</span></div>
                        <div><span className="text-slate-500">Resolved:</span> <span className="text-crisis-green font-bold">{analytics.resolved_incidents}</span></div>
                        <div><span className="text-slate-500">Avg Response:</span> <span className="text-crisis-cyan font-bold">{analytics.avg_response_time} min</span></div>
                    </div>
                </div>
            )}

            <div className="grid lg:grid-cols-3 gap-4">
                {/* Incident List */}
                <div className="card overflow-hidden">
                    <div className="p-3 border-b border-white/5">
                        <span className="text-sm font-semibold text-white">Select Incident</span>
                    </div>
                    <div className="overflow-y-auto" style={{ maxHeight: 500 }}>
                        {incidents.map(inc => (
                            <div key={inc.id}
                                onClick={() => generateReport(inc)}
                                className={`p-3 border-b border-white/3 cursor-pointer transition-colors
                     ${selectedInc?.id === inc.id ? 'bg-crisis-blue/10' : 'hover:bg-white/2'}`}>
                                <div className="flex items-center justify-between">
                                    <span className="text-xs font-mono text-slate-400">{inc.id}</span>
                                    <span className={`badge ${inc.severity === 'Critical' ? 'badge-critical' : inc.severity === 'High' ? 'badge-high' : 'badge-medium'}`}>
                                        {inc.severity}
                                    </span>
                                </div>
                                <div className="text-sm text-white mt-1">{inc.incident_type}</div>
                                <div className="text-xs text-slate-500">{inc.location}</div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Report Preview */}
                <div className="lg:col-span-2">
                    {selectedInc ? (
                        <div className="card overflow-hidden">
                            <div className="p-3 border-b border-white/5 flex items-center justify-between">
                                <span className="text-sm font-semibold text-white">Emergency Report</span>
                                <button onClick={handlePrint} className="btn-primary flex items-center gap-1 text-xs py-1.5 px-3">
                                    <Printer size={14} /> Print Report
                                </button>
                            </div>
                            <div ref={reportRef} className="p-6 space-y-4 text-sm bg-navy-950">
                                <div>
                                    <h1 className="text-lg font-bold text-white">🚨 Emergency Incident Report</h1>
                                    <p className="text-xs text-slate-500">CrisisFlow Emergency Response Platform</p>
                                </div>

                                <div className="bg-navy-800 rounded-lg p-4 space-y-2">
                                    <h2 className="text-sm font-semibold text-crisis-blue">Incident Summary</h2>
                                    <div className="grid grid-cols-2 gap-2 text-xs">
                                        <div><span className="text-slate-500">Incident ID:</span> <span className="text-white">{selectedInc.id}</span></div>
                                        <div><span className="text-slate-500">Type:</span> <span className="text-white">{selectedInc.incident_type}</span></div>
                                        <div><span className="text-slate-500">Location:</span> <span className="text-white">{selectedInc.location}</span></div>
                                        <div><span className="text-slate-500">Severity:</span>
                                            <span className={`badge ml-1 ${selectedInc.severity === 'Critical' ? 'badge-critical' : 'badge-high'}`}>
                                                {selectedInc.severity}
                                            </span>
                                        </div>
                                        <div><span className="text-slate-500">People at Risk:</span> <span className="text-white">{selectedInc.people_at_risk}</span></div>
                                        <div><span className="text-slate-500">Status:</span> <span className="text-white">{selectedInc.status}</span></div>
                                        {selectedInc.floor && <div><span className="text-slate-500">Floor:</span> <span className="text-white">{selectedInc.floor}</span></div>}
                                        {selectedInc.spread_risk && <div><span className="text-slate-500">Spread Risk:</span> <span className="text-white">{selectedInc.spread_risk}</span></div>}
                                    </div>
                                    {selectedInc.description && (
                                        <div className="text-xs text-slate-300 mt-2 pt-2 border-t border-white/5">
                                            {selectedInc.description}
                                        </div>
                                    )}
                                </div>

                                {rec && (
                                    <div className="bg-navy-800 rounded-lg p-4 space-y-2 border border-crisis-purple/20">
                                        <h2 className="text-sm font-semibold text-crisis-purple">🧠 AI Recommendation</h2>
                                        <div className="grid grid-cols-2 gap-2 text-xs">
                                            {rec.fire_station_name && <div><span className="text-slate-500">🚒 Fire Station:</span> <span className="text-white">{rec.fire_station_name}</span></div>}
                                            {rec.ambulance_id && <div><span className="text-slate-500">🚑 Ambulance:</span> <span className="text-white">{rec.ambulance_id}</span></div>}
                                            {rec.hospital_name && <div><span className="text-slate-500">🏥 Hospital:</span> <span className="text-white">{rec.hospital_name}</span></div>}
                                            {rec.route && <div><span className="text-slate-500">🛣️ Route:</span> <span className="text-white">{rec.route}</span></div>}
                                            <div><span className="text-slate-500">⏱️ ETA:</span> <span className="text-crisis-cyan font-bold">{rec.eta_minutes} min</span></div>
                                            <div><span className="text-slate-500">🎯 Confidence:</span> <span className="text-crisis-green font-bold">{rec.confidence}%</span></div>
                                        </div>
                                        <div className="mt-2 space-y-1">
                                            <div className="text-xs font-semibold text-slate-400">Decision Rationale:</div>
                                            {rec.reasons.map((r, i) => (
                                                <div key={i} className="text-xs text-slate-300 flex gap-1">
                                                    <span className="text-crisis-green">✓</span> {r}
                                                </div>
                                            ))}
                                        </div>
                                        {rec.explanation && (
                                            <div className="mt-2 pt-2 border-t border-white/5">
                                                <div className="text-xs font-semibold text-slate-400 mb-1">AI Explanation:</div>
                                                <pre className="text-xs text-slate-300 whitespace-pre-wrap font-sans">{rec.explanation}</pre>
                                            </div>
                                        )}
                                    </div>
                                )}

                                <div className="text-[10px] text-slate-600 pt-3 border-t border-white/5">
                                    Generated by CrisisFlow | {new Date().toLocaleString()} | Data Source: Simulation
                                </div>
                            </div>
                        </div>
                    ) : (
                        <div className="card p-12 text-center">
                            <FileText size={48} className="text-slate-700 mx-auto mb-3" />
                            <div className="text-slate-500">Select an incident to generate a report</div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
